-- Multi-user emoji PIN table for MyKeepsakes
-- Allows individual family members to authenticate with their own PIN

CREATE TABLE public.user_emoji_pins (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  pin_hash TEXT NOT NULL,
  avatar_emoji TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.user_emoji_pins ENABLE ROW LEVEL SECURITY;

-- Allow public read (for PIN hash lookup during login)
CREATE POLICY "Allow public read access to user pins"
ON public.user_emoji_pins
FOR SELECT
USING (true);

-- Allow public update (for PIN changes)
CREATE POLICY "Allow public update access to user pins"
ON public.user_emoji_pins
FOR UPDATE
USING (true);

-- Insert Shawn and Dan's PINs
-- Shawn: 🦅🔐🏠💎 → hash will be generated by client/seed script
INSERT INTO public.user_emoji_pins (email, display_name, avatar_emoji, pin_hash)
VALUES
  ('runx31021@gmail.com', 'Shawn', '🦅', 'temp_shawn_hash'),
  ('danllanes22@gmail.com', 'Dan', '🐘', 'temp_dan_hash');

-- Create trigger for updated_at
CREATE TRIGGER update_user_emoji_pins_updated_at
BEFORE UPDATE ON public.user_emoji_pins
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();
